"use client"
import { FormEvent, useState } from "react"
import { Button } from "@/components/ui/button"
export function StatutoryCancellationForm() {
  const [sent, setSent] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const detail = [`Physical address: ${data.get("address")}`, `Camp/event: ${data.get("event")}`, `Booking date: ${data.get("booking_date")}`, `Reason: ${data.get("reason") || "Not provided"}`].join("\n"); const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), email: data.get("email"), subject: "Statutory cancellation request", message: detail, source_page: "/terms", save_submission: true }) }); if (response.ok) { setSent(true); event.currentTarget.reset() } }
  if (sent) return <p className="rounded-xl bg-green-50 p-4 text-sm text-green-800" role="status">Your cancellation request has been submitted for processing.</p>
  return <form onSubmit={submit} className="not-prose mt-6 space-y-4 rounded-xl border border-border bg-card p-5"><div><label htmlFor="cancel-name">Your full name *</label><input id="cancel-name" name="name" required className="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2" /></div><div><label htmlFor="cancel-email">Your email address *</label><input id="cancel-email" name="email" type="email" required className="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2" /></div><div><label htmlFor="cancel-address">Your physical address *</label><textarea id="cancel-address" name="address" required rows={3} className="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2" /></div><div><label htmlFor="cancel-event">Name of the camp / event registered for *</label><input id="cancel-event" name="event" required className="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2" /></div><div><label htmlFor="cancel-date">Date the booking was made *</label><input id="cancel-date" name="booking_date" type="date" required className="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2" /></div><div><label htmlFor="cancel-reason">Reason for cancellation (optional)</label><textarea id="cancel-reason" name="reason" rows={3} className="mt-1 w-full rounded-lg border border-input bg-background px-3 py-2" /></div><Button type="submit">Submit cancellation request</Button></form>
}
