import os

lines = []
lines.append("const CAMP_FROM_EMAIL = 'Singhs Camp <singhscampuk@devanhaar.com>'")
lines.append("")
lines.append("function escapeHtml(value: string): string {")
lines.append("  return value")
lines.append("    .replace(/&/g, '&amp;')")
lines.append("    .replace(/</g, '&lt;')")
lines.append("    .replace(/>/g, '&gt;')")
lines.append('    .replace(/"/g, \'&quot;\')')
lines.append("    .replace(/'/g, '&#039;')")
lines.append("}")
lines.append("")

# Under Review Email
lines.append("export async function sendApplicationUnderReviewEmail(params: {")
lines.append("  to: string")
lines.append("  firstName: string")
lines.append("  applicationId: string")
lines.append("}): Promise<boolean> {")
lines.append("  if (\!process.env.RESEND_API_KEY) {")
lines.append("    console.warn('[Camp Email] Skipping under-review email - RESEND_API_KEY not configured')")
lines.append("    return false")
lines.append("  }")
lines.append("")
lines.append("  const { Resend } = await import('resend')")
lines.append("  const resend = new Resend(process.env.RESEND_API_KEY)")
lines.append("  const escapedName = escapeHtml(params.firstName)")
lines.append("")
lines.append("  const html = `")
lines.append('    <div style="font-family:Arial,Helvetica,sans-serif;color:#111;max-width:600px;margin:0 auto;">')
lines.append('      <h2 style="margin:0 0 16px;">Thank you for your application, ${escapedName}\!</h2>')
lines.append('      <p>We have received your Singhs Camp application and it is now <strong>under review</strong>.</p>')
lines.append('      <p><strong>What happens next?</strong></p>')
lines.append('      <ul style="line-height:1.8;">')
lines.append('        <li>Our team will review your application carefully.</li>')
lines.append('        <li>If your application is <strong>accepted</strong>, your payment will be captured and you will receive a confirmation email with further details about the camp.</li>')
lines.append('        <li>If your application is <strong>not accepted</strong>, your payment hold will be released in full and you will be notified by email.</li>')
lines.append('      </ul>')
lines.append('      <p>The review process may take a few days. If you have any questions in the meantime, please reply to this email or contact us at <a href="mailto:singhscampuk@devanhaar.com">singhscampuk@devanhaar.com</a>.</p>')
lines.append('      <p style="margin-top:24px;">Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh\!</p>')
lines.append('      <p><strong>Singhs Camp Team</strong><br/>Devanhaar</p>')
lines.append('    </div>')
lines.append("  `")
lines.append("")
lines.append("  const text = `Thank you for your application, ${params.firstName}\!")
lines.append("")
lines.append("We have received your Singhs Camp application and it is now under review.")
lines.append("")
lines.append("What happens next?")
lines.append("- Our team will review your application carefully.")
lines.append("- If your application is accepted, your payment will be captured and you will receive a confirmation email with further details about the camp.")
lines.append("- If your application is not accepted, your payment hold will be released in full and you will be notified by email.")
lines.append("")
lines.append("The review process may take a few days. If you have any questions in the meantime, please contact us at singhscampuk@devanhaar.com.")
lines.append("")
lines.append("Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh\!")
lines.append("")
lines.append("Singhs Camp Team")
lines.append("Devanhaar`")
lines.append("")
lines.append("  try {")
lines.append("    await resend.emails.send({")
lines.append("      from: CAMP_FROM_EMAIL,")
lines.append("      to: params.to,")
lines.append("      subject: 'Your Singhs Camp Application is Under Review',")
lines.append("      html,")
lines.append("      text,")
lines.append("    })")
lines.append("    console.log('[Camp Email] Under-review email sent to', params.to)")
lines.append("    return true")
lines.append("  } catch (err) {")
lines.append("    console.error('[Camp Email] Failed to send under-review email:', err)")
lines.append("    return false")
lines.append("  }")
lines.append("}")
lines.append("")

# Approved Email
lines.append("export async function sendApplicationApprovedEmail(params: {")
lines.append("  to: string")
lines.append("  firstName: string")
lines.append("}): Promise<boolean> {")
lines.append("  if (\!process.env.RESEND_API_KEY) {")
lines.append("    console.warn('[Camp Email] Skipping approved email - RESEND_API_KEY not configured')")
lines.append("    return false")
lines.append("  }")
lines.append("")
lines.append("  const { Resend } = await import('resend')")
lines.append("  const resend = new Resend(process.env.RESEND_API_KEY)")
lines.append("  const escapedName = escapeHtml(params.firstName)")
lines.append("")
lines.append("  const html = `")
lines.append('    <div style="font-family:Arial,Helvetica,sans-serif;color:#111;max-width:600px;margin:0 auto;">')
lines.append('      <h2 style="margin:0 0 16px;">Congratulations, ${escapedName}\!</h2>')
lines.append('      <p>We are pleased to let you know that your Singhs Camp application has been <strong>accepted</strong>.</p>')
lines.append('      <p>Your payment has now been captured. You will receive further details about the camp closer to the date, including location, schedule, and what to bring.</p>')
lines.append('      <p>If you have any questions, please reply to this email or contact us at <a href="mailto:singhscampuk@devanhaar.com">singhscampuk@devanhaar.com</a>.</p>')
lines.append('      <p style="margin-top:24px;">Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh\!</p>')
lines.append('      <p><strong>Singhs Camp Team</strong><br/>Devanhaar</p>')
lines.append('    </div>')
lines.append("  `")
lines.append("")
lines.append("  const text = `Congratulations, ${params.firstName}\!")
lines.append("")
lines.append("We are pleased to let you know that your Singhs Camp application has been accepted.")
lines.append("")
lines.append("Your payment has now been captured. You will receive further details about the camp closer to the date, including location, schedule, and what to bring.")
lines.append("")
lines.append("If you have any questions, please contact us at singhscampuk@devanhaar.com.")
lines.append("")
lines.append("Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh\!")
lines.append("")
lines.append("Singhs Camp Team")
lines.append("Devanhaar`")
lines.append("")
lines.append("  try {")
lines.append("    await resend.emails.send({")
lines.append("      from: CAMP_FROM_EMAIL,")
lines.append("      to: params.to,")
lines.append("      subject: 'Your Singhs Camp Application Has Been Accepted\!',")
lines.append("      html,")
lines.append("      text,")
lines.append("    })")
lines.append("    console.log('[Camp Email] Approved email sent to', params.to)")
lines.append("    return true")
lines.append("  } catch (err) {")
lines.append("    console.error('[Camp Email] Failed to send approved email:', err)")
lines.append("    return false")
lines.append("  }")
lines.append("}")
lines.append("")

# Declined Email
lines.append("export async function sendApplicationDeclinedEmail(params: {")
lines.append("  to: string")
lines.append("  firstName: string")
lines.append("}): Promise<boolean> {")
lines.append("  if (\!process.env.RESEND_API_KEY) {")
lines.append("    console.warn('[Camp Email] Skipping declined email - RESEND_API_KEY not configured')")
lines.append("    return false")
lines.append("  }")
lines.append("")
lines.append("  const { Resend } = await import('resend')")
lines.append("  const resend = new Resend(process.env.RESEND_API_KEY)")
lines.append("  const escapedName = escapeHtml(params.firstName)")
lines.append("")
lines.append("  const html = `")
lines.append('    <div style="font-family:Arial,Helvetica,sans-serif;color:#111;max-width:600px;margin:0 auto;">')
lines.append('      <h2 style="margin:0 0 16px;">Update on your Singhs Camp Application</h2>')
lines.append('      <p>Dear ${escapedName},</p>')
lines.append('      <p>Thank you for applying to Singhs Camp. After careful review, we regret to inform you that your application has <strong>not been accepted</strong> on this occasion.</p>')
lines.append('      <p>Your payment hold has been <strong>fully released</strong> and no charge has been made. The refund should appear in your account within 5-10 business days.</p>')
lines.append('      <p>We encourage you to apply again in the future. If you have any questions, please reply to this email or contact us at <a href="mailto:singhscampuk@devanhaar.com">singhscampuk@devanhaar.com</a>.</p>')
lines.append('      <p style="margin-top:24px;">Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh\!</p>')
lines.append('      <p><strong>Singhs Camp Team</strong><br/>Devanhaar</p>')
lines.append('    </div>')
lines.append("  `")
lines.append("")
lines.append("  const text = `Update on your Singhs Camp Application")
lines.append("")
lines.append("Dear ${params.firstName},")
lines.append("")
lines.append("Thank you for applying to Singhs Camp. After careful review, we regret to inform you that your application has not been accepted on this occasion.")
lines.append("")
lines.append("Your payment hold has been fully released and no charge has been made. The refund should appear in your account within 5-10 business days.")
lines.append("")
lines.append("We encourage you to apply again in the future. If you have any questions, please contact us at singhscampuk@devanhaar.com.")
lines.append("")
lines.append("Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh\!")
lines.append("")
lines.append("Singhs Camp Team")
lines.append("Devanhaar`")
lines.append("")
lines.append("  try {")
lines.append("    await resend.emails.send({")
lines.append("      from: CAMP_FROM_EMAIL,")
lines.append("      to: params.to,")
lines.append("      subject: 'Update on Your Singhs Camp Application',")
lines.append("      html,")
lines.append("      text,")
lines.append("    })")
lines.append("    console.log('[Camp Email] Declined email sent to', params.to)")
lines.append("    return true")
lines.append("  } catch (err) {")
lines.append("    console.error('[Camp Email] Failed to send declined email:', err)")
lines.append("    return false")
lines.append("  }")
lines.append("}")
lines.append("")

with open("lib/camp-applicant-emails.ts", "w") as f:
    f.write("\n".join(lines))

print(f"Written {len(lines)} lines")
